server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/usermgnt
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
app1:
    messages:
      saveSuccess: 
      saveFail: 
mail:
  host: smtp.gmail.com
  port: 587
  username: myemail@gmail.com
  password: mypassword
  properties:
    starttls.enable: true